kind: Pod
apiVersion: v1
metadata:
  name: phpfpm-nginx-example
  namespace: demo
  labels:
    app: phpfpm
spec:
  volumes:
    - name: phpfpm-application
      configMap:
        name: phpfpm-application
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - image: php:8.0.9-fpm-alpine
      name: phpfpm
      volumeMounts:
        - name: phpfpm-application
          mountPath: /app/index.php
          subPath: index.php
    - image: nginx:1.21.1-alpine
      name: nginx
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
